#!/usr/bin/env python3

import sys, os, platform

from lang.parser import _run

def _start_program():
    try:
        sys.argv[1]
    except:
        print(f"yell-r1, running on {platform.system()} {platform.release()}.")
        print("Press ^D to run the code.")
        print("")
        _input = []
        for line in sys.stdin:
            _input.append(line)
        _run(_input)
    else:
        if os.path.exists(sys.argv[1]):
            with open(sys.argv[1]) as f:
                _input = f.readlines()
                _run(_input)
        else:
            print(f'The file {sys.argv[1]} doesn\'t seem to exist.')

try:
    _start_program()
except:
    sys.exit(1)